import React from "react";

type Props = {};

const Verbs150 = (props: Props) => {
  return (
    <div className="t-container">
      <h2 className="t-title">Verbs 100 -150</h2>
      <table>
        <thead>
          <tr>
            <th>Infinitive</th>
            <th>Past Simple</th>
            <th>Past Participle</th>
            <th>Translation</th>
            <th>Pronunciation</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>fly</td>
            <td>flew</td>
            <td>flown</td>
            <td>volar</td>
            <td>flu:</td>
          </tr>
          <tr>
            <td>forget</td>
            <td>forgot</td>
            <td>forgotten</td>
            <td>olvidar</td>
            <td>fəˈgɒt</td>
          </tr>
          <tr>
            <td>forgive</td>
            <td>forgave</td>
            <td>forgiven</td>
            <td>perdonar</td>
            <td>fəˈgeɪv</td>
          </tr>
          <tr>
            <td>freeze</td>
            <td>froze</td>
            <td>frozen</td>
            <td>congelar</td>
            <td>frəʊz</td>
          </tr>
          <tr>
            <td>get</td>
            <td>got</td>
            <td>got</td>
            <td>obtener</td>
            <td>gat</td>
          </tr>
          <tr>
            <td>give</td>
            <td>gave</td>
            <td>given</td>
            <td>dar</td>
            <td>giv</td>
          </tr>
          <tr>
            <td>go</td>
            <td>went</td>
            <td>gone</td>
            <td>ir</td>
            <td>gou</td>
          </tr>
          <tr>
            <td>grow</td>
            <td>grew</td>
            <td>grown</td>
            <td>crecer</td>
            <td>gru:</td>
          </tr>
          <tr>
            <td>hang</td>
            <td>hung</td>
            <td>hung</td>
            <td>colgar</td>
            <td>hʌŋ</td>
          </tr>
          <tr>
            <td>have</td>
            <td>had</td>
            <td>had</td>
            <td>tener</td>
            <td>hæd</td>
          </tr>
          <tr>
            <td>hear</td>
            <td>heard</td>
            <td>heard</td>
            <td>oír</td>
            <td>hɜ:rd</td>
          </tr>
          <tr>
            <td>hide</td>
            <td>hid</td>
            <td>hidden</td>
            <td>esconder</td>
            <td>hɪd</td>
          </tr>
          <tr>
            <td>hit</td>
            <td>hit</td>
            <td>hit</td>
            <td>golpear</td>
            <td>hɪt</td>
          </tr>
          <tr>
            <td>keep</td>
            <td>kept</td>
            <td>kept</td>
            <td>mantener</td>
            <td>kept</td>
          </tr>
          <tr>
            <td>kneel</td>
            <td>knelt</td>
            <td>knelt</td>
            <td>arrodillarse</td>
            <td>nelt</td>
          </tr>
          <tr>
            <td>knit</td>
            <td>knitted</td>
            <td>knitted</td>
            <td>tejer</td>
            <td>nɪt</td>
          </tr>
          <tr>
            <td>know</td>
            <td>knew</td>
            <td>known</td>
            <td>saber/conocer</td>
            <td>nou</td>
          </tr>
          <tr>
            <td>lay</td>
            <td>laid</td>
            <td>laid</td>
            <td>poner</td>
            <td>leid</td>
          </tr>
          <tr>
            <td>lead</td>
            <td>led</td>
            <td>led</td>
            <td>liderar</td>
            <td>led</td>
          </tr>
          <tr>
            <td>learn</td>
            <td>learnt</td>
            <td>learnt</td>
            <td>aprender</td>
            <td>lɜ:nt</td>
          </tr>
          <tr>
            <td>leave</td>
            <td>left</td>
            <td>left</td>
            <td>dejar</td>
            <td>left</td>
          </tr>
          <tr>
            <td>lend</td>
            <td>lent</td>
            <td>lent</td>
            <td>prestar</td>
            <td>lent</td>
          </tr>
          <tr>
            <td>let</td>
            <td>let</td>
            <td>let</td>
            <td>dejar</td>
            <td>let</td>
          </tr>
          <tr>
            <td>lie</td>
            <td>lay</td>
            <td>lain</td>
            <td>mentir</td>
            <td>lei</td>
          </tr>
          <tr>
            <td>light</td>
            <td>lit</td>
            <td>lit</td>
            <td>encender</td>
            <td>lɪt</td>
          </tr>
          <tr>
            <td>lose</td>
            <td>lost</td>
            <td>lost</td>
            <td>perder</td>
            <td>loust</td>
          </tr>
          <tr>
            <td>make</td>
            <td>made</td>
            <td>made</td>
            <td>hacer</td>
            <td>meik</td>
          </tr>
          <tr>
            <td>mean</td>
            <td>meant</td>
            <td>meant</td>
            <td>significar</td>
            <td>ment</td>
          </tr>
          <tr>
            <td>meet</td>
            <td>met</td>
            <td>met</td>
            <td>conocer</td>
            <td>met</td>
          </tr>
          <tr>
            <td>pay</td>
            <td>paid</td>
            <td>paid</td>
            <td>pagar</td>
            <td>peid</td>
          </tr>
          <tr>
            <td>put</td>
            <td>put</td>
            <td>put</td>
            <td>poner</td>
            <td>put</td>
          </tr>
          <tr>
            <td>quit</td>
            <td>quit</td>
            <td>quit</td>
            <td>dejar</td>
            <td>kwɪt</td>
          </tr>
          <tr>
            <td>read</td>
            <td>read</td>
            <td>read</td>
            <td>leer</td>
            <td>ri:d</td>
          </tr>
          <tr>
            <td>ride</td>
            <td>rode</td>
            <td>ridden</td>
            <td>montar</td>
            <td>roud</td>
          </tr>
          <tr>
            <td>ring</td>
            <td>rang</td>
            <td>rung</td>
            <td>sonar</td>
            <td>ræŋ</td>
          </tr>
          <tr>
            <td>rise</td>
            <td>rose</td>
            <td>risen</td>
            <td>levantarse</td>
            <td>rouz</td>
          </tr>
          <tr>
            <td>run</td>
            <td>ran</td>
            <td>run</td>
            <td>correr</td>
            <td>rʌn</td>
          </tr>
          <tr>
            <td>say</td>
            <td>said</td>
            <td>said</td>
            <td>decir</td>
            <td>seid</td>
          </tr>
          <tr>
            <td>see</td>
            <td>saw</td>
            <td>seen</td>
            <td>ver</td>
            <td>si:</td>
          </tr>
          <tr>
            <td>sell</td>
            <td>sold</td>
            <td>sold</td>
            <td>vender</td>
            <td>səʊld</td>
          </tr>
          <tr>
            <td>send</td>
            <td>sent</td>
            <td>sent</td>
            <td>enviar</td>
            <td>sent</td>
          </tr>
          <tr>
            <td>set</td>
            <td>set</td>
            <td>set</td>
            <td>poner</td>
            <td>set</td>
          </tr>
          <tr>
            <td>shake</td>
            <td>shook</td>
            <td>shaken</td>
            <td>agitar</td>
            <td>ʃuk</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default Verbs150;
