import React from "react";

type Props = {};

const Verbs100 = (props: Props) => {
  return (
    <div className="t-container">
      <h2>Verbs 50- 100</h2>
      <table>
        <thead>
          <tr>
            <th>Infinitive</th>
            <th>Past Simple</th>
            <th>Past Participle</th>
            <th>Translation</th>
            <th>Pronunciation</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>send</td>
            <td>sent</td>
            <td>sent</td>
            <td>enviar</td>
            <td>sent</td>
          </tr>
          <tr>
            <td>get</td>
            <td>got</td>
            <td>got</td>
            <td>obtener</td>
            <td>gat</td>
          </tr>
          <tr>
            <td>run</td>
            <td>ran</td>
            <td>run</td>
            <td>correr</td>
            <td>rʌn</td>
          </tr>
          <tr>
            <td>move</td>
            <td>moved</td>
            <td>moved</td>
            <td>mover</td>
            <td>mu:v</td>
          </tr>
          <tr>
            <td>live</td>
            <td>lived</td>
            <td>lived</td>
            <td>vivir</td>
            <td>livd</td>
          </tr>
          <tr>
            <td>open</td>
            <td>opened</td>
            <td>opened</td>
            <td>abrir</td>
            <td>ˈəʊp(ə)n</td>
          </tr>
          <tr>
            <td>start</td>
            <td>started</td>
            <td>started</td>
            <td>empezar</td>
            <td>stɑ:rt</td>
          </tr>
          <tr>
            <td>play</td>
            <td>played</td>
            <td>played</td>
            <td>jugar</td>
            <td>pleid</td>
          </tr>
          <tr>
            <td>hold</td>
            <td>held</td>
            <td>held</td>
            <td>sostener</td>
            <td>held</td>
          </tr>
          <tr>
            <td>spend</td>
            <td>spent</td>
            <td>spent</td>
            <td>gastar</td>
            <td>spent</td>
          </tr>
          <tr>
            <td>choose</td>
            <td>chose</td>
            <td>chosen</td>
            <td>elegir</td>
            <td>tʃu:z</td>
          </tr>
          <tr>
            <td>hear</td>
            <td>heard</td>
            <td>heard</td>
            <td>oír</td>
            <td>hɜ:rd</td>
          </tr>
          <tr>
            <td>turn</td>
            <td>turned</td>
            <td>turned</td>
            <td>girar</td>
            <td>tɜ:nd</td>
          </tr>
          <tr>
            <td>cut</td>
            <td>cut</td>
            <td>cut</td>
            <td>cortar</td>
            <td>kat</td>
          </tr>
          <tr>
            <td>add</td>
            <td>added</td>
            <td>added</td>
            <td>añadir</td>
            <td>æd</td>
          </tr>
          <tr>
            <td>allow</td>
            <td>allowed</td>
            <td>allowed</td>
            <td>permitir</td>
            <td>əˈlaʊ</td>
          </tr>
          <tr>
            <td>fill</td>
            <td>filled</td>
            <td>filled</td>
            <td>llenar</td>
            <td>fil</td>
          </tr>
          <tr>
            <td>pass</td>
            <td>passed</td>
            <td>passed</td>
            <td>pasar</td>
            <td>pa:s</td>
          </tr>
          <tr>
            <td>sell</td>
            <td>sold</td>
            <td>sold</td>
            <td>vender</td>
            <td>səʊld</td>
          </tr>
          <tr>
            <td>bring</td>
            <td>brought</td>
            <td>brought</td>
            <td>traer</td>
            <td>brɔ:t</td>
          </tr>
          <tr>
            <td>buy</td>
            <td>bought</td>
            <td>bought</td>
            <td>comprar</td>
            <td>bɔ:t</td>
          </tr>
          <tr>
            <td>drive</td>
            <td>drove</td>
            <td>driven</td>
            <td>conducir</td>
            <td>drav</td>
          </tr>
          <tr>
            <td>fall</td>
            <td>fell</td>
            <td>fallen</td>
            <td>caer</td>
            <td>fel</td>
          </tr>
          <tr>
            <td>feel</td>
            <td>felt</td>
            <td>felt</td>
            <td>sentir</td>
            <td>felt</td>
          </tr>
          <tr>
            <td>fight</td>
            <td>fought</td>
            <td>fought</td>
            <td>luchar</td>
            <td>fɔ:t</td>
          </tr>
          <tr>
            <td>speak</td>
            <td>spoke</td>
            <td>spoken</td>
            <td>hablar</td>
            <td>spouk</td>
          </tr>
          <tr>
            <td>teach</td>
            <td>taught</td>
            <td>taught</td>
            <td>enseñar</td>
            <td>tɔ:t</td>
          </tr>
          <tr>
            <td>think</td>
            <td>thought</td>
            <td>thought</td>
            <td>pensar</td>
            <td>θɔ:t</td>
          </tr>
          <tr>
            <td>understand</td>
            <td>understood</td>
            <td>understood</td>
            <td>entender</td>
            <td>ˌʌndəˈstænd</td>
          </tr>
          <tr>
            <td>wear</td>
            <td>wore</td>
            <td>worn</td>
            <td>usar</td>
            <td>wo:r</td>
          </tr>
          <tr>
            <td>win</td>
            <td>won</td>
            <td>won</td>
            <td>ganar</td>
            <td>wan</td>
          </tr>
          <tr>
            <td>write</td>
            <td>wrote</td>
            <td>written</td>
            <td>escribir</td>
            <td>rəut</td>
          </tr>
          <tr>
            <td>catch</td>
            <td>caught</td>
            <td>caught</td>
            <td>atrapar</td>
            <td>kɔ:t</td>
          </tr>
          <tr>
            <td>choose</td>
            <td>chose</td>
            <td>chosen</td>
            <td>elegir</td>
            <td>tʃu:z</td>
          </tr>
          <tr>
            <td>do</td>
            <td>did</td>
            <td>done</td>
            <td>hacer</td>
            <td>dɪd</td>
          </tr>
          <tr>
            <td>draw</td>
            <td>drew</td>
            <td>drawn</td>
            <td>dibujar</td>
            <td>dru:</td>
          </tr>
          <tr>
            <td>drink</td>
            <td>drank</td>
            <td>drunk</td>
            <td>beber</td>
            <td>dræŋk</td>
          </tr>
          <tr>
            <td>drive</td>
            <td>drove</td>
            <td>driven</td>
            <td>conducir</td>
            <td>drav</td>
          </tr>
          <tr>
            <td>eat</td>
            <td>ate</td>
            <td>eaten</td>
            <td>comer</td>
            <td>i:t</td>
          </tr>
          <tr>
            <td>fall</td>
            <td>fell</td>
            <td>fallen</td>
            <td>caer</td>
            <td>fel</td>
          </tr>
          <tr>
            <td>feed</td>
            <td>fed</td>
            <td>fed</td>
            <td>alimentar</td>
            <td>fed</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default Verbs100;
