import React from "react";

type Props = {};

const Verbs50 = (props: Props) => {
  return (
    <div className="t-container">
      <h2 className="t-title">Verbs 0 - 50</h2>
      <table>
        <thead>
          <tr>
            <th>Infinitive</th>
            <th>Past Simple</th>
            <th>Past Participle</th>
            <th>Translation</th>
            <th>Pronunciation</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>know</td>
            <td>knew</td>
            <td>known</td>
            <td>saber/conocer</td>
            <td>nou</td>
          </tr>
          <tr>
            <td>eat</td>
            <td>ate</td>
            <td>eaten</td>
            <td>comer</td>
            <td>i:t</td>
          </tr>
          <tr>
            <td>go</td>
            <td>went</td>
            <td>gone</td>
            <td>ir</td>
            <td>gou</td>
          </tr>
          <tr>
            <td>see</td>
            <td>saw</td>
            <td>seen</td>
            <td>ver</td>
            <td>si:</td>
          </tr>
          <tr>
            <td>take</td>
            <td>took</td>
            <td>taken</td>
            <td>tomar</td>
            <td>teik</td>
          </tr>
          <tr>
            <td>come</td>
            <td>came</td>
            <td>come</td>
            <td>venir</td>
            <td>kam</td>
          </tr>
          <tr>
            <td>give</td>
            <td>gave</td>
            <td>given</td>
            <td>dar</td>
            <td>giv</td>
          </tr>
          <tr>
            <td>find</td>
            <td>found</td>
            <td>found</td>
            <td>encontrar</td>
            <td>faund</td>
          </tr>
          <tr>
            <td>think</td>
            <td>thought</td>
            <td>thought</td>
            <td>pensar</td>
            <td>θɔ:t</td>
          </tr>
          <tr>
            <td>tell</td>
            <td>told</td>
            <td>told</td>
            <td>contar</td>
            <td>to:ld</td>
          </tr>
          <tr>
            <td>become</td>
            <td>became</td>
            <td>become</td>
            <td>convertirse</td>
            <td>bikam</td>
          </tr>
          <tr>
            <td>show</td>
            <td>showed</td>
            <td>shown</td>
            <td>mostrar</td>
            <td>ʃou</td>
          </tr>
          <tr>
            <td>leave</td>
            <td>left</td>
            <td>left</td>
            <td>dejar</td>
            <td>left</td>
          </tr>
          <tr>
            <td>call</td>
            <td>called</td>
            <td>called</td>
            <td>llamar</td>
            <td>kɔ:ld</td>
          </tr>
          <tr>
            <td>try</td>
            <td>tried</td>
            <td>tried</td>
            <td>intentar</td>
            <td>traid</td>
          </tr>
          <tr>
            <td>mean</td>
            <td>meant</td>
            <td>meant</td>
            <td>significar</td>
            <td>ment</td>
          </tr>
          <tr>
            <td>set</td>
            <td>set</td>
            <td>set</td>
            <td>poner</td>
            <td>set</td>
          </tr>
          <tr>
            <td>build</td>
            <td>built</td>
            <td>built</td>
            <td>construir</td>
            <td>bilt</td>
          </tr>
          <tr>
            <td>break</td>
            <td>broke</td>
            <td>broken</td>
            <td>romper</td>
            <td>brouk</td>
          </tr>
          <tr>
            <td>speak</td>
            <td>spoke</td>
            <td>spoken</td>
            <td>hablar</td>
            <td>spouk</td>
          </tr>
          <tr>
            <td>pay</td>
            <td>paid</td>
            <td>paid</td>
            <td>pagar</td>
            <td>peid</td>
          </tr>
          <tr>
            <td>stand</td>
            <td>stood</td>
            <td>stood</td>
            <td>estar de pie</td>
            <td>stu:d</td>
          </tr>
          <tr>
            <td>lose</td>
            <td>lost</td>
            <td>lost</td>
            <td>perder</td>
            <td>loust</td>
          </tr>
          <tr>
            <td>win</td>
            <td>won</td>
            <td>won</td>
            <td>ganar</td>
            <td>wan</td>
          </tr>
          <tr>
            <td>catch</td>
            <td>caught</td>
            <td>caught</td>
            <td>atrapar</td>
            <td>kɔ:t</td>
          </tr>
          <tr>
            <td>wear</td>
            <td>wore</td>
            <td>worn</td>
            <td>usar</td>
            <td>wo:r</td>
          </tr>
          <tr>
            <td>make</td>
            <td>made</td>
            <td>made</td>
            <td>hacer</td>
            <td>meik</td>
          </tr>
          <tr>
            <td>feel</td>
            <td>felt</td>
            <td>felt</td>
            <td>sentir</td>
            <td>felt</td>
          </tr>
          <tr>
            <td>put</td>
            <td>put</td>
            <td>put</td>
            <td>poner</td>
            <td>put</td>
          </tr>
          <tr>
            <td>bring</td>
            <td>brought</td>
            <td>brought</td>
            <td>traer</td>
            <td>brɔ:t</td>
          </tr>
          <tr>
            <td>begin</td>
            <td>began</td>
            <td>begun</td>
            <td>empezar</td>
            <td>bigin</td>
          </tr>
          <tr>
            <td>keep</td>
            <td>kept</td>
            <td>kept</td>
            <td>mantener</td>
            <td>kept</td>
          </tr>
          <tr>
            <td>write</td>
            <td>wrote</td>
            <td>written</td>
            <td>escribir</td>
            <td>rəut</td>
          </tr>
          <tr>
            <td>stand</td>
            <td>stood</td>
            <td>stood</td>
            <td>estar de pie</td>
            <td>stu:d</td>
          </tr>
          <tr>
            <td>let</td>
            <td>let</td>
            <td>let</td>
            <td>dejar</td>
            <td>let</td>
          </tr>
          <tr>
            <td>mean</td>
            <td>meant</td>
            <td>meant</td>
            <td>significar</td>
            <td>ment</td>
          </tr>
          <tr>
            <td>set</td>
            <td>set</td>
            <td>set</td>
            <td>poner</td>
            <td>set</td>
          </tr>
          <tr>
            <td>build</td>
            <td>built</td>
            <td>built</td>
            <td>construir</td>
            <td>bilt</td>
          </tr>
          <tr>
            <td>break</td>
            <td>broke</td>
            <td>broken</td>
            <td>romper</td>
            <td>brouk</td>
          </tr>
          <tr>
            <td>speak</td>
            <td>spoke</td>
            <td>spoken</td>
            <td>hablar</td>
            <td>spouk</td>
          </tr>
          <tr>
            <td>pay</td>
            <td>paid</td>
            <td>paid</td>
            <td>pagar</td>
            <td>peid</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default Verbs50;
